-- Criação da tabela
CREATE TABLE client (
    idade INTEGER NOT NULL,
    code_client BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR(25) NOT NULL,
    PRIMARY KEY (code_client)
);

-- Inserção de dados
INSERT INTO client (code_client, nome, cpf, idade) VALUES (1, 'João Silva', '12345678901', 30);

